[package]
name = "rust_book_gcd"
version = "0.1.0"
authors = ["Bruno Flores <bruno@apnic.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
